homeassistant:
  name: Home
  latitude: 35.69
  longitude: 139.69
  elevation: 0
  unit_system: metric
  time_zone: Asia/Tokyo
  customize:
    switch.dining_light:
      google_assistant_type: light
    climate.dining_aircon:
      friendly_name: ダイニングのエアコン
    script.oyasumi:
      friendly_name: もう寝よう
    script.ohayou:
      friendly_name: おはよう

http:
  api_password: !secret http_password

group: !include groups.yaml
automation: !include automations.yaml

frontend:

config:

updater:

conversation:

history:

logbook:

map:

sun:

tts:
  - platform: google

cloud:

ios:

sensor:
  - platform: yr

media_player:
  - platform: cast

google_assistant:
  project_id: kihomeextender
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - climate
    - script
        
switch:
  platform: command_line
  switches:
    dining_light:
      friendly_name: ダイニングのライト
      command_on: "/home/homeassistant/.homeassistant/bin/dining_light_on.sh"
      command_off: "/home/homeassistant/.homeassistant/bin/dining_light_off.sh"
    living_bookshelf_light:
      friendly_name: リビングの本棚ライト
      command_on: "/home/homeassistant/.homeassistant/bin/living_ifttt_light.sh home_bookshelflight_on"
      command_off: "/home/homeassistant/.homeassistant/bin/living_ifttt_light.sh home_bookshelflight_off"
    living_stand_light:
      friendly_name: リビングのスタンドライト
      command_on: "/home/homeassistant/.homeassistant/bin/living_ifttt_light.sh home_standlight_on"
      command_off: "/home/homeassistant/.homeassistant/bin/living_ifttt_light.sh home_standlight_off"

climate dining_aircon:
  platform: command_line
  command_off: "/home/homeassistant/.homeassistant/bin/dining_aircon_off.sh"
  command_heater: "/home/homeassistant/.homeassistant/bin/dining_aircon_on.sh"
#  command_cooler: 
  name: Dining Aircon
  min_temp: 20
  max_temp: 30
  target_temp: 26

shell_command:
  script_oyasumi: "/home/homeassistant/.homeassistant/bin/script_oyasumi.sh"
  script_ohayou: "/home/homeassistant/.homeassistant/bin/script_ohayou.sh"

script:
  oyasumi:
    sequence:
    - service: shell_command.script_oyasumi
  ohayou:
    sequence:
    - service: shell_command.script_ohayou

